var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/alerts/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_uwgyh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o0n49o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0eczp_u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/[root-of-the-server]__1gux7cw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_1rx542o._.js")
R.c("server/chunks/ssr/_1y4ig_s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0w6mzq5._.js")
R.c("server/chunks/ssr/_06bge-3._.js")
R.c("server/chunks/ssr/node_modules_next_1f68z_s._.js")
R.m(60850)
module.exports=R.m(60850).exports
